# Default configuration for waste district vision
# This file should work out-of-the-box for most users

camera:
  index: 0  # Default camera (most systems)
  
storage:
  # Relative paths - will be created automatically
  primary_dir: "./data/collected_frames"
  fallback_dir: "./data/backup_frames"
  
collection:
  burst_duration: 10.0
  burst_fps: 2.0
  cooldown_sec: 3.0
  min_frames_per_hour: 50
  max_frames_per_hour: 200

motion_detection:
  min_blob_area: 0.0015
  scale_factor: 0.5
  persist_frames: 3

frame_analysis:
  frame_history_size: 3
  min_difference_threshold: 0.03
  use_roi_diversity: true

system:
  headless: false  # Set to true for server deployment